services:
  - type: worker
    name: fitness-pal-bot
    env: python
    repo: https://github.com/MadinaTadjidinova/fitnessPO.git
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TOKEN
        sync: false  # укажешь вручную в Render → Environment
